const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes(1pc)',
    category: 'breakfast',
    price: 225,
    img: './images/item-1.jpeg',
    desc: `The BEST Fluffy Buttermilk Pancakes you’ll ever try – promise! This easy to follow pancake recipe yields super delicious and totally amazing pancakes every time! So much better than a box mix`,
  },
  {
    id: 2,
    title: 'Chesse burger with fried chips',
    category: 'lunch',
    price: 200,
    img: './images/item-2.jpeg',
    desc: `Enjoy these delicious and flavourful Ready to eat Breakfast to Dinner Combo full meal to alleviate your taste buds. Ready in just 10 mins.`,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 115,
    img: './images/item-3.jpeg',
    desc: `Don’t cry me a river, cry me a milkshake!! Sip, sip, hooray!`,
  },
  {
    id: 4,
    title: 'Bread-omlett special(1pc)',
    category: 'breakfast',
    price: 180,
    img: './images/item-4.jpeg',
    desc: `Take a bite of omelette, filled with the rich goodness of hot cheese. Don't burn your tongue! Follow it with a bite of bread. Let the flavors and texture meld into your mouth. `,
  },
  {
    id: 5,
    title: 'special burger(1pc)',
    category: 'lunch',
    price: 80,
    img: './images/item-5.jpeg',
    desc: `If you put an egg on a burger, you've got breakfast But if you order from here you'll get delicious breakfast.`,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 169,
    img: './images/item-6.jpeg',
    desc: `After a sip of Oreo shake , the corners of her mouth curved into a smile and this is how all her sadness melts away, When life gets tough, shake it. `,
  },
  {
    id: 7,
    title: 'Cold coffee with Icecream',
    category: 'breakfast',
    price: 79,
    img: './images/item-9.jpeg',
    desc: `Life is bored? so get some special, kunki chatpata jaruri hai`,
  },
  {
    id: 8,
    title: 'Aaloo Burger(3pcs)',
    category: 'lunch',
    price: 99,
    img: './images/item-8.JPEG',
    desc: `Don't expect anyone to be perfect. ... by his looks, Kyunki "Aalu hi French fries hai.`,
  },
  {
    id: 9,
    title: 'cheese overflow(1pc)',
    category: 'breakfast',
    price: 130,
    img: './images/item-7.jpeg',
    desc: `A burger without cheese is like a hug without a squeeze; now THAT is a tasty burger; ground beef between your teeth; eyes on the fries`,
  },
  {
  id:10,
  title: 'Strawberry Shake',
  category: 'shakes',
  price: 110,
  img: './images/item-10.jpeg',
  desc: `When life gives you strawberries and ice cream, make milkshakes. Why do you make a milkshake? I'll make for you`,
},
  
];
export default menu;